#dev#
---
version: "3.7"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    ports:
     - $FRESHRSS_PORT:80
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/freshrss:/config
    restart: unless-stopped
