---
version: "3.7"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    networks:
     - traefik-proxy
    ports:
     - $FRESHRSS_PORT:80
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-proxy
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=HostHeader(`freshrss.$SECONDDOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=chain-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=$FRESHRSS_PORT"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/freshrss:/config
    restart: unless-stopped

networks:
  traefik-proxy:
    external: true
