---
version: '3.7'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    networks:
     - traefik-proxy
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-proxy
      ## HTTP Routers
      - "traefik.http.routers.homeassistant-rtr.entrypoints=https"
      - "traefik.http.routers.homeassistant-rtr.rule=HostHeader(`homeassistant.$SECONDDOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=3000"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/homeassistant:/config
    restart: always

networks:
  traefik-proxy:
    external: true
