---
version: '3.7'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - "$PORTAINER_PORT:9000"
    environment:
      - TZ=$TZ
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DOCKERDIR/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    restart: unless-stopped
