---
version: "3.7"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    ports:
      - 4000:3000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/docker-data/wikijs/config:/config
      - /home/docker-data/wikijs/data:/data
    restart: unless-stopped
