---
version: "3.7"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    ports:
      - $WIKIJS_PORT:3000
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/wikijs:/config
      - $DOCKERDIR/wikijs/data:/data
    restart: unless-stopped
