###################################################
###################################################
##### WhitehomeIO Sonarr Docker-Compose File ######
###################################################
###################################################
---
version: "3.3"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - sonarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  collector-downloads:
    driver: local
    driver_opts:
      type: none
      device: /nfs/content-gateway/inbox
      o: bind

  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /nfs/media/
      o: bind

  sonarr:
    driver: local
    driver_opts:
      type: none
      device: /nfs/docker-data/sonarr
      o: bind
