---
version: "3.7"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    networks:
     - traefik-public
    ports:
      - 4003:8181
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.tautulli-http.entrypoints=http
      - traefik.http.routers.tautulli-http.rule=Host(`tautulli.int.whitehome.io`)
      - traefik.http.routers.tautulli-https.entrypoints=https
      - traefik.http.routers.tautulli-https.rule=Host(`tautulli.int.whitehome.io`)
      - traefik.http.routers.tautulli-https.tls=true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/tautulli:/config
      - /docker-data/tautulli/logs:/logs
    restart: unless-stopped

networks:
  traefik-public:
    external: true
