---
version: "3.7"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    ports:
      - 4011:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/tautulli:/config
      - /home/docker/appdata/tautulli/logs:/logs
    restart: unless-stopped
