###################################################
###################################################
### WhitehomeIO organizrV2 Docker-Compose File ####
###################################################
###################################################
---
version: "3.7"
services:
 organizr:
    image: organizrtools/organizr-v2
    container_name: organizr-v2
    networks:
     - traefik-public
    ports:
     - 4002:80
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
    volumes:
     - /docker-data/organizr:/config
    restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
