---
version: "3.7"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    networks:
     - traefik-public
     - traefik-internal
    ports:
     - 4011:80
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.freshrss-http.entrypoints=http
      - traefik.http.routers.freshrss-http.rule=Host(`freshrss.int.whitehome.io`)
      - traefik.http.routers.freshrss-https.entrypoints=https
      - traefik.http.routers.freshrss-https.rule=Host(`freshrss.int.whitehome.io`)
      - traefik.http.routers.freshrss-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/freshrss:/config
    restart: unless-stopped

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
