---
version: "3.7"
services:
  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr-v2
    networks:
      - traefik-public
      - traefik-internal
    ports:
      - 4002:80
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.organizr-http.entrypoints=http
      - traefik.http.routers.organizr-http.rule=Host(`organizr.int.whitehome.io`)
      - traefik.http.routers.organizr-https.entrypoints=https
      - traefik.http.routers.organizr-https.rule=Host(`organizr.int.whitehome.io`)
      - traefik.http.routers.organizr-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/organizr:/config
    restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
  traefik-internal:
    external: false
