version: "3.7"
# Docker compose file for Digital Ocean Droplets

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
  socket_proxy:
    external:
      name: socket_proxy

services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    ports:
      - 80:8181
      - 8080:8080
      - 443:4443
    volumes:
      - "/docker/appdata/nginx-proxy-manager:/config:rw"

  unifi-controller:
    container_name: unifi-controller
    image: ghcr.io/linuxserver/unifi-controller
    restart: unless-stopped
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MEM_LIMIT=1024M #optional
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    volumes:
      - $DOCKERDIR/unifi:/config

  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=wireguard.whitehome.io #optional
      - SERVERPORT=51820 #optional
      - PEERS=4 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.229.180.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    ports:
      - 51820:51820/udp
    volumes:
      - $DOCKERDIR/wireguard/config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  heimdall:
    container_name: heimdall
    image: ghcr.io/linuxserver/heimdall
    restart: unless-stopped
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/heimdall/config>:/config
    ports:
      - 4000:80
      - 4430:443
