version: "3.7"
# TEST DOCKER-COMPOSE


#####
# This serves as a testing docker-compose file
# New services are deployed here before merging into the main compose file
####


## Compose Structure
#  service:
#    image:
#    container_name:
#    restart:
#    command:
#    networks:
#    ports:
#    security_opt:
#    environment:
#    secrets:
#    volumes:
#    labels:


#### SERVICES

services:
  grav:
    image: ghcr.io/linuxserver/grav
    container_name: grav
    restart: unless-stopped
    networks:
      - t2_proxy
#    ports:
#      - $GRAV_PORT:80
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERTESTDIR/grav:/config
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.grav-rtr.entrypoints=websecure"
      - "traefik.http.routers.grav-rtr.rule=HostHeader(`grav.$DOMAINNAME`)"
      - "traefik.http.routers.grav-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.grav-rtr.middlewares=chain-no-auth@file"
#      - "traefik.http.routers.grav-rtr.middlewares=middlewares-basic-auth@file"
      - "traefik.http.routers.grav-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.grav-rtr.service=grav-svc"
      - "traefik.http.services.grav-svc.loadbalancer.server.port=80"


##### NETWORKS

networks:
  t2_proxy:
    external:
      name: t2_proxy
  frontend:
    external:
      name: frontend
  default:
    driver: bridge


#### SECRETS

secrets:
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  authelia_notifier_smtp_password:
    file: $SECRETSDIR/authelia_notifier_smtp_password
  cloudflare_api_key:
    file: $SECRETSDIR/cloudflare_api_key
  cloudflare_email:
    file: $SECRETSDIR/cloudflare_email
  http_password:
    file: $SECRETSDIR/http_password
  postgres_password:
    file: $SECRETSDIR/postgres_password


#### EOF ####
