version: "3.7"
# CLOUD DOCKER-COMPOSE


####
# This serves as the docker-compose file for cloud deployment
# Any service that needs 100 uptime, or outside connection is deployed
####


##### SERVICES

services:

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jlesage/nginx-proxy-manager
    restart: unless-stopped
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    ports:
      - 8181:8181
      - 80:80
      - 443:443
    volumes:
      - $DOCKERDIR/nginx-proxy-manager:/config:rw


#### NETWORKS

networks:
  frontend:
    external:
      name: frontend
  default:
    driver: bridge
