version: "3.7"
# Docker Compose for testing new apps before deploying into main stack

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  frontend:
    external:
      name: frontend
  default:
    driver: bridge

########################### SERVICES
services:
