version: "3.7"
# MAIN DOCKER-COMPOSE

########################### NETWORKS
networks:
  frontend:
    driver: bridge
    internal: false
  backend:
    driver: bridge
    internal: true

services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $ORGANIZR_PORT:80
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/organizr:/config

  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $HEIMDALL_PORT_01:80
      - $HEIMDALL_PORT_02:443
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/heimdall:/config

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $FRESHRSS_PORT:80
    security_opt:
     - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/freshrss:/config

  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $WIKIJS_PORT:3000
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/wikijs:/config
      - $DOCKERDIR/wikijs/data:/data

  mealie:
    image: hkotel/mealie
    container_name: mealie
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $MEALIE_PORT:80
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - db_type=sqlite
    volumes:
      - $DOCKERDIR/mealie/data/:/app/data

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $TAUTULLI_PORT:8181
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/tautulli:/config
      - $DOCKERDIR/tautulli/logs:/logs

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $JACKETT_PORT:9117
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
       - $DOCKERDIR/jackett:/config

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $HYDRA2_PORT:5076
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/hydra2:/config

  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $AIRSONIC_PORT:4040
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
#      - CONTEXT_PATH=<URL_BASE> #optional
#      - JAVA_OPTS=<options> #optional
    volumes:
      - $DOCKERDIR/airsonic:/config
      - $MEDIADIR/Audio/Collection:/music
      - $MEDIADIR/Audio/Playlists:/playlists
      - $MEDIADIR/Audio/Podcasts:/podcasts

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $NAVIDROME_PORT:4533
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # Optional: put your config options customization here. Examples:
      - ND_SCANINTERVAL=1m
      - ND_LOGLEVEL=info
      - ND_BASEURL=""
    volumes:
      - $DOCKERDIR/navidrome:/data"
      - $MEDIADIR/Audio/Collection:/music"

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $LIDARR_PORT:8686
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $MEDIADIR/Audio/Music:/music
      - $MEDIAGATEDIR/process/Audio/Music:/downloads

  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/homeassistant:/config
#    devices:
#      - /path/to/device:/path/to/device
