version: "3.7"
# Docker compose file for Digital Ocean Droplets

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  wireguard:
    external:
      name: wireguard
  default:
    driver: bridge

services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=wireguard.whitehome.io #optional
      - SERVERPORT=51820 #optional
      - PEERS=4 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.229.180.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    ports:
      - 51820:51820/udp
    volumes:
      - $DOCKERDIR/wireguard/config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
