version: "3.7"
# MAIN DOCKER-COMPOSE

########################### NETWORKS
networks:
  frontend:
    driver: bridge
    internal: false
  backend:
    driver: bridge
    internal: true

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $JACKETT_PORT:9117
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
       - $DOCKERDIR/jackett:/config

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $HYDRA2_PORT:5076
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/hydra2:/config

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - $LIDARR_PORT:8686
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $MEDIADIR/Audio/Music:/music
      - $MEDIAGATEDIR/process/Audio/Music:/downloads

  homeassistant:
    image: ghcr.io/linuxserver/homeassistant
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/homeassistant:/config
#    devices:
#      - /path/to/device:/path/to/device

  joplin:
    image: joplin/server:latest
    container_name: joplin
    depends_on:
        - postgres
    restart: unless-stopped
    ports:
      - $JOPLIN_PORT:22300
    networks:
      - frontend
      - backend
    environment:
#        - APP_BASE_URL=$APP_BASE_URL
        - DB_CLIENT=pg
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DATABASE=$POSTGRES_DATABASE
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PORT=$POSTGRES_PORT
        - POSTGRES_HOST=db

  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 5432:5432
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - APP_PORT=22300
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DATABASE
    volumes:
        - $DOCKERDIR/postgres:/var/lib/postgresql/data
