version: "3.7"
# Docker compose file for Digital Ocean Droplets

networks:
  frontend:
    driver: bridge

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    ports:
      - 81:81
      - 80:80
      - 443:443
    volumes:
      - $DOCKERDIR/nginx-proxy-manager:/config:rw
