version: "3.7"
# TEST DOCKER-COMPOSE

#####
# This serves as a testing docker-compose file
# New services are deployed here before merging into the main compose file
####

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  frontend:
    external:
      name: frontend
  default:
    driver: bridge

########################### SERVICES
services:
### Testing Services ###

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    networks:
      - t2_proxy
#    ports:
#      - $GHOST_PORT:2368
    security_opt:
     - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    environment:
#       - database__client=mysql
#       - database__connection__host=mysql
#       - database__connection__user=${MYSQL_USER}
#       - database__connection__password=${MYSQL_PASSWORD}
#       - database__connection__database=${MYSQL_DATABASE}
       - url=http://ghost.whitehome.io
       - NODE_ENV=production
    links:
      - mysql
    volumes:
#      - $DOCKERDIR/ghost/volumes/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings
      - $DOCKERDIR/ghost/content:/var/lib/ghost/content:z
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ghost-rtr.entrypoints=websecure"
      - "traefik.http.routers.ghost-rtr.rule=Host(`ghost.$DOMAINNAME`)"
      - "traefik.http.routers.ghost-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.ghost-rtr.middlewares=chain-no-auth@file"
  #    - "traefik.http.routers.overseerr-rtr.middlewares=middlewares-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.ghost-rtr.service=ghost-svc"
      - "traefik.http.services.ghost-svc.loadbalancer.server.port=2368"
