version: "3.7"
# TEST DOCKER-COMPOSE

#####
# This serves as a testing docker-compose file
# New services are deployed here before merging into the main compose file
####

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  frontend:
    external:
      name: frontend
  default:
    driver: bridge

########################### SERVICES
services:
### Testing Services ###

  firefly:
    image: fireflyiii/core:latest
    volumes:
      - $DOCKERDIR/firefly:/var/www/html/storage/upload
    ports:
      - 80:8080
    depends_on:
      - mariadb-ff
      
  mariadb-ff:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - $DOCKERDIR/mariadb-ffiii:/var/lib/mysql
