---
version: "3.7"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "$JACKETT_PORT:9117"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/jackett:/config
      - $DOCKERDIR/jackett/blackhole:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
