---
version: "3.7"
services:
  calibre-web:
    image: linuxserver/calibre-web
    networks:
      - traefik-public
      - traefik-internal
    ports:
      - 4014:8083
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.calibre-http.entrypoints=http
      - traefik.http.routers.calibre-http.rule=Host(`calibre.int.whitehome.io`)
      - traefik.http.routers.calibre-https.entrypoints=https
      - traefik.http.routers.calibre-https.rule=Host(`calibre.int.whitehome.io`)
      - traefik.http.routers.calibre-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /docker-data/calibre:/config
      - p/Literature/eBooks:/books
    restart: unless-stopped

volumes:
  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
