---
version: "3.7"
services:
  calibre-web:
    image: linuxserver/calibre-web
    networks:
      - traefik-public
    ports:
      - 4014:8083
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.calibre-http.entrypoints=web
      - traefik.http.routers.calibre-http.rule=Host(`calibre.int.whitehome.io`)
      - traefik.http.routers.calibre-https.entrypoints=websecure
      - traefik.http.routers.calibre-https.rule=Host(`calibre.int.whitehome.io`)
      - traefik.http.routers.calibre-https.tls=true
      - traefik.http.routers.calibre-https.tls.certresolver=default
      - traefik.http.routers.calibre-http.middlewares=calibre-https@docker
      - traefik.http.middlewares.calibre-https.redirectscheme.scheme=https
      - traefik.http.middlewares.calibre-https.redirectScheme.permanent=true
    volumes:
      - /docker-data/calibre:/config
      - p/Literature/eBooks:/books
    restart: unless-stopped

volumes:
  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
