#dev#
---
version: "3.7"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    ports:
      - $TAUTULLI_PORT:8181
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/tautulli:/config
      - $DOCKERDIR/tautulli/logs:/logs
    restart: unless-stopped
