---
version: "3.7"
services:
    # Organizr - Unified Frontend
  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr-v2
    networks:
      - default
    ports:
      - $ORGANIZR_PORT:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/organizr:/config
    restart: unless-stopped

  # Heimdall - Unified Dashboard
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    networks:
      - default
    ports:
      - $HEIMDALL_PORT_01:80
      - $HEIMDALL_PORT_02:443
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/heimdall:/config
    restart: unless-stopped

  ############################# INDEXERS

  # Jackett - Torrent proxy
  # Set url_base in Jackett settings if using PathPrefix
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
     - default
    ports:
      - "$JACKETT_PORT:9117"
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/jackett:/config
      - /home/jackett/blackhole:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  # NZBHydra2 - NZB meta search
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    networks:
     - default
    ports:
      - $HYDRA2_PORT:5076
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/hydra2:/config
      - nova-nzb:/downloads
    restart: unless-stopped

  ############################# PVRS

  # Lidarr - Music Management
  # Set url_base in lidarr settings if using PathPrefix
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    networks:
     - default
    ports:
      - "$LIDARR_PORT:8686"
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/lidarr:/config
      - nova-media:/media
      - nova-downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  # Radarr - Movie management
  # Set url_base in radarr settings if using PathPrefix
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
     - default
    ports:
      - $RADARR_PORT:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker-data/radarr:/config
      - nova-media:/media
      - nova-downloads:/downloads
    restart: unless-stopped

  # Sonarr - TV Shows management
  # Set url_base in sonarr settings if using PathPrefix
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
     - default
    ports:
      - $SONARR_PORT:8989
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/sonarr:/config
      - nova-media:/media
      - nova-downloads:/downloads
    restart: unless-stopped

  # Lazylibrarian  – Ebooks and Management
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    networks:
     - default
    ports:
      - $LAZYLIBRARIAN_PORT:5299
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /home/lazylibrarian:/config
      - nova-downloads:/downloads
      - nova-media:/books
    restart: unless-stopped

  ############################# MEDIA

  # Calibre-web  – Ebooks and Management (Plex of Ebooks)
  calibre-web:
    image: linuxserver/calibre-web
    networks:
      - default
    ports:
      - $CALIBRE_PORT:8083
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      DOCKER_MODS: linuxserver/calibre-web:calibre
    volumes:
      - /home/calibre:/config
      - nova-media-ebooks:/books
    restart: unless-stopped

  # Ombi - Media Requests
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    networks:
      - default
    ports:
      - $OMBI_PORT:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
     - /home/ombi:/config
    restart: unless-stopped

  # Tautulli - Previously PlexPy. Plex statistics and monitoring
  # Set HTTP Root in Tautulli settings if using PathPrefix
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    networks:
     - default
    ports:
      - $TAUTULLI_PORT:8181
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/tautulli:/config
      - /home/tautulli/logs:/logs
    restart: unless-stopped

  ############################# WEB

  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    networks:
     - default
    ports:
      - $WIKIJS_PORT:3000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/wikijs:/config
      - /home/wikijs/data:/data
    restart: unless-stopped

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    networks:
     - default
    ports:
     - $FRESHRSS_PORT:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/freshrss:/config
    restart: unless-stopped


########################### NETWORKS

networks:
  default:
    driver: bridge

secrets:
  cloudflare_email:
    file: $SECRETSDIR/cloudflare_email
  cloudflare_api_key:
    file: $SECRETSDIR/cloudflare_api_key
  my_email:
    file: $SECRETSDIR/my_email
