###################################################
###################################################
##### WhitehomeIO Radarr Docker-Compose File ######
###################################################
###################################################
---
version: "3.7"
services:
 radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 4006:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker-data/radarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    restart: unless-stopped


volumes:
  collector-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/inbox
      o: bind

  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
