###################################################
###################################################
##### WhitehomeIO wikijs Docker-Compose File ######
###################################################
###################################################
---
version: "3.7"
services:
 wikijs:
   image: linuxserver/wikijs
   container_name: wikijs
   networks:
    - traefik-public
   ports:
     - 4010:3000
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
   volumes:
     - /docker-data/wikijs:/config
     - /docker-data/wikijs/data:/data
   restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
