---
version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
     - traefik-public
     - traefik-internal
    ports:
      - 4005:8989
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.sonarr-http.entrypoints=http
      - traefik.http.routers.sonarr-http.rule=Host(`sonarr.int.whitehome.io`)
      - traefik.http.routers.sonarr-https.entrypoints=https
      - traefik.http.routers.sonarr-https.rule=Host(`sonarr.int.whitehome.io`)
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.docker.network=traefik-internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker-data/sonarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    restart: unless-stopped

volumes:
  nova-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/
      o: bind
  nova-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
