version: "3"
services:
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - path to data:/config
    environment:
      - APP_URL= your application URL IE 192.168.10.1:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=secret user password
      - PGID=1000
      - PUID=1000
    ports:
      - "8080:80"
