---
<<<<<<< refs/remotes/origin/master
version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
=======
version: '2'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
>>>>>>> added portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
<<<<<<< refs/remotes/origin/master
      - /docker/appdata/portainer:/data
    restart: unless-stopped
=======
      - portainer_data:/data

volumes:
  portainer_data:~/appdata/portainer
>>>>>>> added portainer
