---
version: "2.1"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=your timezone, eg Europe/London
    volumes:
      - path to data:/config
    ports:
      - 9283:80
    restart: unless-stopped
