###################################################
###################################################
##### WhitehomeIO MariaDB Docker-Compose File #####
###################################################
###################################################
---
version: "3.7"
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Ma2ZdORCNYiWzuVh1F
      - TZ=America/Chicago
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=dockeruser
      - MYSQL_PASSWORD=3flwOoleDbyNpJw8Jx4g2IWM
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /docker-data/mariadb:/config
    restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
