---
version: "3.7"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - 4021:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/heimdall:/config
    restart: unless-stopped

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    ports:
     - 4000:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/freshrss:/config
    restart: unless-stopped

  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    ports:
      - 4010:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/wikijs:/config
      - /home/docker/appdata/wikijs/data:/data
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 4014:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/jackett:/config
    restart: unless-stopped

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    ports:
      - 4013:5076
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/hydra2:/config
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    ports:
      - 4011:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/tautulli:/config
      - /home/docker/appdata/tautulli/logs:/logs
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    ports:
      - 4012:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/docker/appdata/ombi/config:/config
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    ports:
      - 4020:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/docker/appdata/organizr:/config
    restart: unless-stopped
