---
### Rancher Compose file for PVR applications ###
version: "2"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    ports:
      - 4004:8686
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/lidarr:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 4006:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /docker-data/radarr:/config
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 4005:8989
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/sonarr:/config
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    ports:
      - 4009:5299
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /home/lazylibrarian:/config
    restart: unless-stopped
