###################################################
###################################################
###### WhitehomeIO stack Docker-Compose File ######
###################################################
###################################################
---
version: "3.3"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - lidarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    ports:
      - 4004:8686
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - radarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    ports:
      - 4006:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - sonarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    ports:
      - 4005:8989
    restart: unless-stopped

  jackett:
   image: linuxserver/jackett
   container_name: jackett
   ports:
     - 4007:9117
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
     - AUTO_UPDATE=true #optional
     - RUN_OPTS=run options here #optional
   volumes:
     - jackett:/config
     - jackett-blackhole:/downloads
   restart: unless-stopped

  ombi:
   image: linuxserver/ombi
   container_name: ombi
   ports:
     - 4008:3579
   environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    - BASE_URL=/ombi #optional
   volumes:
    - ombi:/config
   restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - lazylibrarian:/config
      - collector-downloads:/downloads
      - collector-media:/books
    ports:
      - 4009:5299
    restart: unless-stopped

volumes:
  collector-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/inbox
      o: bind

  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

  lidarr:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/lidarr
      o: bind

  radarr:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/radarr
      o: bind

  sonarr:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/sonarr
      o: bind

  jackett:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/jackett
      o: bind

  jackett-blackhole:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/jackett/blackhole
      o: bind

  ombi:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/ombi
      o: bind

  lazylibrarian:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/lazylibrarian
      o: bind
