###################################################
###################################################
###### WhitehomeIO stack Docker-Compose File ######
###################################################
###################################################
---
version: "3.3"
services:
 heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    networks:
      - traefik-public
    ports:
      - 4000:80
      - 4001:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - heimdall:/config
    restart: unless-stopped

 organizr:
    image: organizrtools/organizr-v2
    container_name: organizr-v2
    networks:
     - traefik-public
    ports:
     - 4002:80
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
    volumes:
     - organizr:/config
    restart: unless-stopped


volumes:
  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/heimdall
      o: bind

  organizr:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/organizr
      o: bind


networks:
  traefik-public:
    external: true
