###################################################
###################################################
### WhitehomeIO Media Stack Docker-Compose File ###
###################################################
###################################################
---
version: "3.3"
services:
 tautulli:
   image: linuxserver/tautulli
   container_name: tautulli
   networks:
     - traefik-public
   ports:
     - 4003:8181
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
   volumes:
     - tautulli:/config
     - tautulli-logs:/logs
   restart: unless-stopped


volumes:
  tautulli:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/tautulli
      o: bind

  tautulli-logs:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/tautulli/logs
      o: bind


networks:
  traefik-public:
    external: true
