---
version: '3.7'
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    ports:
      - 4012:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/appdata/ombi/config:/config
    restart: unless-stopped
