###################################################
###################################################
###### WhitehomeIO Ombi Docker-Compose File #######
###################################################
###################################################
---
version: '3.3'
services:
 ombi:
  image: linuxserver/ombi
  container_name: ombi
  ports:
     - 4001:3579
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
    - BASE_URL=/ombi #optional
  volumes:
    - ombi:/config
  restart: unless-stopped

volumes:
  ombi:
    driver: local
    driver_opts:
      type: none
      device: /nfs/docker-data/ombi
      o: bind
