ls###################################################
###################################################
##### WhitehomeIO Lidarr Docker-Compose File ######
###################################################
###################################################
---
version: "3.3"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - lidarr:/config
      - collector-media:/media
      - collector-downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

volumes:
  collector-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/inbox
      o: bind

  collector-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

  lidarr:
    driver: local
    driver_opts:
      type: none
      device: /smb/docker-data/lidarr
      o: bind
