---
version: "3.7"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
     - traefik-public
    ports:
      - 4007:9117
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.jackett-http.entrypoints=http
      - traefik.http.routers.jackett-http.rule=Host(`jackett.int.whitehome.io`)
      - traefik.http.routers.jackett-https.entrypoints=https
      - traefik.http.routers.jackett-https.rule=Host(`jackett.int.whitehome.io`)
      - traefik.http.routers.jackett-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    volumes:
      - /docker-data/jackett:/config
      - /docker-data/jackett/blackhole:/downloads
    restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
