---
version: "3.7"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    networks:
     - traefik-public
    ports:
      - 4004:8686
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-public
      - traefik.http.routers.lidarr-http.entrypoints=http
      - traefik.http.routers.lidarr-http.rule=Host(`lidarr.int.whitehome.io`)
      - traefik.http.routers.lidarr-https.entrypoints=https
      - traefik.http.routers.lidarr-https.rule=Host(`lidarr.int.whitehome.io`)
      - traefik.http.routers.lidarr-https.tls=true
      - traefik.http.routers.lidarr-http.middlewares=lidarr-https@docker
      - traefik.http.middlewares.lidarr-https.redirectscheme.scheme=https
      - traefik.http.middlewares.lidarr-https.redirectScheme.permanent=true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /docker-data/lidarr:/config
      - nova-media:/media
      - nova-downloads:/downloads
    restart: unless-stopped

volumes:
  nova-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/
      o: bind
  nova-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  traefik-public:
    external: true
