---
version: '3.7'
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    networks:
      - traefik-public
    ports:
      - 4008:3579
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.ombi-http.entrypoints=http
      - traefik.http.routers.ombi-http.rule=Host(`ombi.int.whitehome.io`)
      - traefik.http.routers.ombi-https.entrypoints=https
      - traefik.http.routers.ombi-https.rule=Host(`ombi.int.whitehome.io`)
      - traefik.http.routers.ombi-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=/ombi #optional
    volumes:
     - /docker-data/ombi:/config
    restart: unless-stopped

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
