---
version: '3.7'
services:
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    networks:
     - traefik-public
    ports:
      - 4009:5299
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.lazylibrarian-http.entrypoints=http
      - traefik.http.routers.lazylibrarian-http.rule=Host(`lazylibrarian.int.whitehome.io`)
      - traefik.http.routers.lazylibrarian-https.entrypoints=https
      - traefik.http.routers.lazylibrarian-https.rule=Host(`lazylibrarian.int.whitehome.io`)
      - traefik.http.routers.lazylibrarian-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /docker-data/lazylibrarian:/config
      - nova-downloads:/downloads
      - nova-media:/books
    restart: unless-stopped


volumes:
  nova-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/inbox
      o: bind

  nova-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
