---
version: "3.7"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    networks:
     - traefik-public
     - traefik-internal
    ports:
      - 4010:3000
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.wikijs-http.entrypoints=http
      - traefik.http.routers.wikijs-http.rule=Host(`wikijs.int.whitehome.io`)
      - traefik.http.routers.wikijs-https.entrypoints=https
      - traefik.http.routers.wikijs-https.rule=Host(`wikijs.int.whitehome.io`)
      - traefik.http.routers.wikijs-https.tls=true
      - traefik.docker.network=traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/wikijs:/config
      - /docker-data/wikijs/data:/data
    restart: unless-stopped

networks:
  traefik-public:
    external: true
  traefik-internal:
    external: false
