---
version: "3.7"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    networks:
     - traefik-proxy
    ports:
      - "$LIDARR_PORT:8686"
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.lidarr-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.lidarr-rtr-bypass.rule=Headers(`X-Api-Key`, `$LIDARR_API_KEY`) || Query(`apikey`, `$LIDARR_API_KEY`)"
      - "traefik.http.routers.lidarr-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.lidarr-rtr.entrypoints=https"
      - "traefik.http.routers.lidarr-rtr.rule=HostHeader(`lidarr.$SECONDDOMAINNAME`)"
      - "traefik.http.routers.lidarr-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.lidarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.lidarr-rtr.middlewares=chain-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.lidarr-rtr.service=lidarr-svc"
      - "traefik.http.routers.lidarr-rtr-bypass.service=lidarr-svc"
      - "traefik.http.services.lidarr-svc.loadbalancer.server.port=$LIDARR_PORT"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    volumes:
      - $DOCKERDIR/lidarr:/config
      - nova-media:/media
      - nova-downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

volumes:
  nova-downloads:
    driver: local
    driver_opts:
      type: none
      device: /smb/content-gateway/
      o: bind
  nova-media:
    driver: local
    driver_opts:
      type: none
      device: /smb/media/
      o: bind

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
  default:
    driver: bridge
