###################################################
###################################################
#### WhitehomeIO freshrss Docker-Compose File #####
###################################################
###################################################
---
version: "3.7"
services:
 freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    networks:
     - traefik-public
    ports:
     - 4011:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/freshrss:/config
    restart: unless-stopped


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
